// internal/assets/tpl/client_extension/liferay-client-extensions-extra-samples/sample-custom-element-svelte/src/App.svelte
<svelte:options customElement={{
  tag: 'sample-custom-element-svelte',
  shadow: 'none'
}}/>

<script>
  import LiferayService from "./lib/LiferayService.js";

  let user = $state({name: null})
  let error = $state(false)
  let errorMessage = $state('')
  let loading = $state(true)

  LiferayService.get('/o/headless-admin-user/v1.0/my-user-account')
  .then((response) => {
    user = response
    loading = false
  })
  .catch((err) => {
    error = true
    errorMessage = err.message
  })
  .finally(() => {
    loading = false
  })
</script>

<div>
  {#if loading}
    <span
        aria-hidden="true"
        class="loading-animation-squares loading-animation-primary loading-animation-md"
    ></span>
  {:else if error}
    <div class="alert alert-danger">
      <strong class="lead">Error:</strong>{errorMessage}
    </div>
  {:else}
    <h1 style="color: var(--primary)">
      Hello from Svelte{', ' + user.name + '!' || '!'}
    </h1>
  {/if}
</div>

// internal/assets/tpl/client_extension/liferay-client-extensions-extra-samples/sample-custom-element-vue/src/App.vue
<script setup>
import {ref} from 'vue'
import LiferayService from "./services/LiferayService.js";

const user = ref(null)
const error = ref(false)
const errorMessage = ref('')
const loading = ref(true)

LiferayService.get('/o/headless-admin-user/v1.0/my-user-account')
.then((response) => {
  user.value = response
  loading.value = false
})
.catch((err) => {
  error.value = true
  errorMessage.value = err.message
})
.finally(() => {
  loading.value = false
})
</script>

<template>
  <span
      v-if="loading"
      aria-hidden="true"
      class="loading-animation-squares loading-animation-primary loading-animation-md"
  ></span>

  <div
      v-if="error"
      class="alert alert-danger">
    <strong class="lead">Error:</strong>{errorMessage}
  </div>
  <h1
      v-else
      style="color: var(--primary)">
    Hello from Vue.js{{ ', ' + user.name + '!' || '!' }}
  </h1>
</template>
